# Generated by Django 4.0.1 on 2022-01-20 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_employee_last_name_alter_employee_age_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('desc', models.CharField(max_length=250)),
                ('datestamp', models.DateField(default='')),
            ],
        ),
    ]
