# Generated by Django 4.0.1 on 2022-01-20 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='datestamp',
            field=models.DateField(),
        ),
    ]
